#!/bin/bash

# If it is not running iteratively, don't do anything
case $- in
    *i*) ;;
      *) echo Please run this script Iteratively, I mean use \"source\" instead of \"\./\" && exit;;
esac

# Install the dependencies
echo Installing system dependencies and libraries && echo
source $(pwd)/win_commands/install

# Run Bot
source $(pwd)/win_commands/run