#!/bin/bash

# If it is not running iteratively, don't do anything
case $- in
    *i*) ;;
      *) echo Please run this script Iteratively, I mean use \"source\" instead of \"\./\" && exit;;
esac

# Chcking some packages on Windows
echo && echo Checking if python3 is installed && echo
python3 --version
echo && echo Checking if mysql is installed && echo
mysql --version
echo && echo Checking if pip3 is installed && echo
pip3 --version
echo && echo And python3, python3-pip, mysql should be installed on your system now && echo

# Setting shortcuts and environment variables
echo && echo Loading shortcuts and environment variables && echo
source $(pwd)/win_commands/shortcuts

# Creating a virtual environment
echo && echo Creating a virtual environment && echo
python3 -m venv env

# Activating the virtual environment
echo && echo Activating the virtual environment && echo
source ./env/bin/activate

# Upgrade wheel package cause it's not up-to-date in some ops
pip3 install wheel
pip3 install --upgrade pip setuptools wheel

# Installing requirements for project
echo && echo Installing the requirements && echo
pip3 install -r requirements.txt

# Everything is done
echo && echo "The installation process is done"
echo "After checking the log, if there is no problem, you can run the bot with \"run\" command"
echo "Press any button to continue to mysql configuration"
read temp

# Configuration for mysql
source ./win_commands/mysql_config